### PR TITLE
Fix login redirect

### LINKED ISSUE #23: Fix redirection to protected pages
User logs in successfully but isn't being redirected to the authenticated page unless the page is refreshed or the login/signup button is clicked again.

### PR DESCRIPTION
**Pull request by Nkoli**
Fixes #23
Fixed, i think. History.push wasn't working for some reason (I also used withRouter to wrap the entire component in export default), so I had to add the isAuthenticated state alongside isLoading and use the redirect component to push to the home page.

### CODE REVIEW

File: src/reducers/githubAuth.js [hunk 1]
```diff
@@ -22,6 +23,13 @@ const githubAuth = (state = initialState, action) => {
         isLoading: true,
         isLoggedIn: false,
       };
+    case AUTHENTICATED:
+      localStorage.setItem("token", JSON.stringify(action.payload.token));
```
Comment (toystars) [inline src/reducers/githubAuth.js]: Ideally, your reducers should only return new state and any side effect should be handled outside of reducers.

File: src/reducers/githubAuth.js [hunk 2]
```diff
@@ -22,6 +23,13 @@ const githubAuth = (state = initialState, action) => {
...
+      return {
+        ...state,
+        isAuthenticated: true,
+        token: action.payload.token,
+      };
     case GITHUB_LOGIN_SUCCESS:
       localStorage.setItem(
```
Comment (toystars) [inline src/reducers/githubAuth.js]: Same as above

**Comment by toystars** [comment]
@Nkoli I left a comment in here

File: src/reducers/githubAuth.js (hunk 1 above)
Comment (Nkoli) [reply src/reducers/githubAuth.js]: Okay

File: src/reducers/githubAuth.js (hunk 2 above)
Comment (Nkoli) [reply src/reducers/githubAuth.js]: just pushed new changes, removed the side effects. Not sure where to add them back, seeing as I needed the action payload in the reducers and it was kind of easier to setItems there. Saw something about store.subscribe and creating state for persisting it but I don't know if that'll be overkill? Also, redirect still doesn't work properly.

File: src/actions/githubAuthAction.js [hunk 3]
```diff
@@ -19,9 +20,16 @@ const githubAuthAction = (code) => {
       })
         .then((response) => response.json())
         .then((data) => {
+          dispatch({
+            type: AUTHENTICATED,
+            payload: { token: data, isAuthenticated: true },
+          });
```
Comment (toystars) [inline src/actions/githubAuthAction.js:29]: I would call make setItem call here before dispatching the `GITHUB_LOGIN_SUCCESS` action. This is a more appropriate place to make the call than in the reducer.

Comment (Nkoli) [reply src/actions/githubAuthAction.js:29]: I should have explained properly. I did make the setItem call there, used `localStorage.setItem('token')`  but then it threw an error about a second argument, using `action.payload.token`  as the second argument didn't work, using just `token` didn't also work. Checked stackoverflow and probably didn't search properly or didn't use the right keywords because I didn't really get any response I understood since I wasn't trying to use the store.subscribe function.

File: src/reducers/githubAuth.js (hunk 2 above)
Comment (toystars) [reply src/reducers/githubAuth.js]: > just pushed new changes, removed the side effects. Not sure where to add them back, seeing as I needed the action payload in the reducers and it was kind of easier to setItems there. Saw something about store.subscribe and creating state for persisting it but I don't know if that'll be overkill? Also, redirect still doesn't work properly.

There are several ways of handling side-effects in redux. And yes, `store.subscribe` is a fast way of doing this. But won't be clean. You will most like;y do as below:

```tsx
function observeStore(store) {
    let currentState = null;

    function handleChange() {
        let nextState = store.getState();
        if (nextState.isAuthenticated !== currentState?.isAuthenticated && nextState.isAuthenticated) {
            // update current state with next state
            currentState = nextState;
            // isAuthenticated state has changed - maybe user just logged in, persist user data
            localStorage.setItem('isLoggedIn', JSON.stringify(nextState.isLoggedIn));
            localStorage.setItem('user', JSON.stringify(nextState.user));
        }
    }

    let unsubscribe = store.subscribe(handleChange);
    return unsubscribe;
}

const store = createStore(appReducer, initialState);

// trigger observe store
const storeObserver = observeStore(store);

// you then unsubscribe from store
storeObserver();
```

File: src/actions/githubAuthAction.js (hunk 3 above)
Comment (toystars) [reply src/actions/githubAuthAction.js:29]: @Nkoli action.payload is only defined in reducers. Nowhere else (except in side effects libraries like redux-saga). If I would call `setItem` before dispatching the action. It would be like this:

```ts
import {
  LOADING,
  AUTHENTICATED,
  GITHUB_LOGIN_SUCCESS,
  GITHUB_LOGIN_FAIL,
} from "./actionTypes";

const url = process.env.REACT_APP_BACKEND_PROXY_URL;

const githubAuthAction = (code) => {
  return (dispatch) => {
    dispatch({ type: LOADING });
    try {
      fetch(`${url}/github_auth/`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ code }),
      })
        .then((response) => response.json())
        .then((data) => {

          // persist necessary data to local storage
          localStorage.setItem('isLoggedIn', true);
          localStorage.setItem('user', JSON.stringify(data));

          dispatch({
            type: AUTHENTICATED,
            payload: { token: data, isAuthenticated: true },
          });
          dispatch({
            type: GITHUB_LOGIN_SUCCESS,
            payload: {
              isLoggedIn: true,
              isAuthenticated: true,
            },
          });
        });
    } catch (error) {
      return dispatch({
        type: GITHUB_LOGIN_FAIL,
      });
    }
  };
};

export default githubAuthAction;
```

File: src/actions/githubAuthAction.js [hunk 4]
```diff
@@ -20,15 +20,19 @@ const githubAuthAction = (code) => {
       })
         .then((response) => response.json())
         .then((data) => {
+          localStorage.setItem("isLoggedIn", true);
+          localStorage.setItem("token", JSON.stringify(data));
```
Comment (toystars) [inline src/actions/githubAuthAction.js]: This ought to be `localStorage.setItem("token", JSON.stringify(data.token));` since the localStorage data is a token

File: src/actions/githubAuthAction.js [hunk 5]
```diff
@@ -20,15 +20,19 @@ const githubAuthAction = (code) => {
...
+          localStorage.setItem("user", JSON.stringify(data));
```
Comment (toystars) [inline src/actions/githubAuthAction.js]: This ought to be `localStorage.setItem("token", JSON.stringify(data.user));` since the localStorage data is a user object.

File: src/reducers/githubAuth.js (hunk 2 above)
Comment (Nkoli) [reply src/reducers/githubAuth.js]: Please when would I need to use this however? I know I said the subscribe function seems like overkill for this particular use case I'm working on but when will it be necessary for me to implement localstorage object like this?

**Review by toystars — APPROVED** [review]
